"""Notification API endpoints — list, mark-read, mark-all-read.

Endpoints:
- GET /notifications               — paginated list with unread_count, filterable
- PATCH /notifications/:id/read    — mark a single notification as read
- POST /notifications/mark-all-read — mark every unread notification as read

Notifications are generated by the NATS consumer in ``notification_generator.py``
from pipeline events (gate.fail, cost_update, steering.action, trust_tier.assigned).
"""

from __future__ import annotations

import logging
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.ext.asyncio import AsyncSession

from src.dashboard.models.notification import (
    NotificationListResponse,
    NotificationRead,
    NotificationType,
    list_notifications,
    mark_all_notifications_read,
    mark_notification_read,
)
from src.db.connection import get_session

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/notifications", tags=["notifications"])


# ---------------------------------------------------------------------------
# List notifications
# ---------------------------------------------------------------------------


@router.get("", response_model=NotificationListResponse)
async def get_notifications(
    unread_only: bool = Query(False, description="Return only unread notifications"),
    notification_type: NotificationType | None = Query(
        None, description="Filter by notification type"
    ),
    limit: int = Query(50, ge=1, le=200, description="Page size"),
    offset: int = Query(0, ge=0, description="Page offset"),
    session: AsyncSession = Depends(get_session),
) -> NotificationListResponse:
    """Return a paginated list of notifications, newest first.

    The response always includes ``unread_count`` reflecting the total number
    of unread notifications across the full table (not limited to the current
    filter or page).
    """
    return await list_notifications(
        session,
        unread_only=unread_only,
        type_filter=notification_type,
        limit=limit,
        offset=offset,
    )


# ---------------------------------------------------------------------------
# Mark single notification as read
# ---------------------------------------------------------------------------


@router.patch("/{notification_id}/read", response_model=NotificationRead)
async def mark_read(
    notification_id: UUID,
    session: AsyncSession = Depends(get_session),
) -> NotificationRead:
    """Mark a single notification as read.

    Returns 404 if the notification does not exist.
    Already-read notifications are idempotently accepted and returned unchanged.
    """
    result = await mark_notification_read(session, notification_id)
    if result is None:
        raise HTTPException(status_code=404, detail="Notification not found")
    return result


# ---------------------------------------------------------------------------
# Mark all notifications as read
# ---------------------------------------------------------------------------


@router.post("/mark-all-read")
async def mark_all_read(
    session: AsyncSession = Depends(get_session),
) -> dict[str, int]:
    """Mark every unread notification as read.

    Returns the count of notifications that were updated.
    """
    updated = await mark_all_notifications_read(session)
    logger.info("mark_all_notifications_read updated=%d", updated)
    return {"updated": updated}
