"""Evidence comment formatting for PR publication.

Formats the evidence comment that accompanies every draft PR.
Epic 0 format: TaskPacket ID, intent summary, verification result.
Full format (Epic 1): adds correlation_id, QA result, expert coverage, loopback summary.

Architecture reference: thestudioarc/15-system-runtime-flow.md — "Standard Agent Evidence Comment"
"""

from __future__ import annotations

from dataclasses import dataclass, field
from uuid import UUID

from src.agent.evidence import EvidenceBundle
from src.intent.intent_spec import IntentSpecRead
from src.verification.gate import VerificationResult

# Marker used to identify TheStudio evidence comments for idempotent updates
EVIDENCE_COMMENT_MARKER = "<!-- thestudio-evidence -->"


def format_evidence_comment(
    evidence: EvidenceBundle,
    intent: IntentSpecRead,
    verification: VerificationResult,
) -> str:
    """Format the evidence comment for a draft PR.

    Contains: TaskPacket ID, intent summary, verification result.
    """
    # Verification summary
    check_lines = []
    for check in verification.checks:
        status = "PASSED" if check.passed else "FAILED"
        check_lines.append(f"| {check.name} | {status} | {check.details or '-'} |")
    checks_table = "\n".join(check_lines) if check_lines else "| - | - | - |"

    # Files changed
    files_list = (
        "\n".join(f"- `{f}`" for f in evidence.files_changed)
        if evidence.files_changed
        else "- None recorded"
    )

    # Acceptance criteria
    criteria_list = (
        "\n".join(f"- [ ] {c}" for c in intent.acceptance_criteria)
        if intent.acceptance_criteria
        else "- None specified"
    )

    return f"""{EVIDENCE_COMMENT_MARKER}

## TheStudio Evidence

| Field | Value |
|-------|-------|
| **TaskPacket ID** | `{evidence.taskpacket_id}` |
| **Intent Version** | v{evidence.intent_version} |
| **Loopback Attempts** | {evidence.loopback_attempt} |
| **Verification** | {'PASSED' if verification.passed else 'FAILED'} |

### Intent Summary

**Goal:** {intent.goal}

### Acceptance Criteria

{criteria_list}

### Verification Results

| Check | Result | Details |
|-------|--------|---------|
{checks_table}

### Files Changed

{files_list}

---
*Generated by TheStudio — AI-augmented software delivery*
"""


@dataclass
class ExpertCoverageSummary:
    """Summary of expert classes consulted and policy triggers."""

    experts_consulted: list[dict[str, object]] = field(default_factory=list)
    policy_triggers: list[str] = field(default_factory=list)


@dataclass
class LoopbackSummary:
    """Summary of verification and QA loopback history."""

    verification_loop_count: int = 0
    verification_failure_categories: list[str] = field(default_factory=list)
    qa_loop_count: int = 0
    qa_defect_categories: list[str] = field(default_factory=list)


@dataclass
class QAResultSummary:
    """Summary of QA validation result for the evidence comment."""

    passed: bool = False
    defect_count: int = 0
    defect_categories: list[str] = field(default_factory=list)
    has_intent_gap: bool = False


def format_full_evidence_comment(
    evidence: EvidenceBundle,
    intent: IntentSpecRead,
    verification: VerificationResult,
    correlation_id: UUID,
    qa_result: QAResultSummary | None = None,
    expert_coverage: ExpertCoverageSummary | None = None,
    loopback: LoopbackSummary | None = None,
) -> str:
    """Format the full evidence comment per 15-system-runtime-flow.md.

    Required contents:
    - TaskPacket id and correlation id
    - Intent version and a one-paragraph summary
    - Acceptance criteria checklist (checkbox format)
    - What changed (high-level)
    - Verification result summary
    - QA result
    - Expert coverage summary
    - Loopback summary
    """
    # Verification summary table
    check_lines = []
    for check in verification.checks:
        status = "PASSED" if check.passed else "FAILED"
        check_lines.append(f"| {check.name} | {status} | {check.details or '-'} |")
    checks_table = "\n".join(check_lines) if check_lines else "| - | - | - |"

    # Files changed
    files_list = (
        "\n".join(f"- `{f}`" for f in evidence.files_changed)
        if evidence.files_changed
        else "- None recorded"
    )

    # Acceptance criteria checklist
    criteria_list = (
        "\n".join(f"- [ ] {c}" for c in intent.acceptance_criteria)
        if intent.acceptance_criteria
        else "- None specified"
    )

    # QA result section
    if qa_result is not None:
        qa_status = "PASSED" if qa_result.passed else "FAILED"
        qa_details = f"**Result:** {qa_status}"
        if qa_result.defect_count > 0:
            cats = ", ".join(qa_result.defect_categories) if qa_result.defect_categories else "none"
            qa_details += f"\n- Defects: {qa_result.defect_count} ({cats})"
        if qa_result.has_intent_gap:
            qa_details += "\n- Intent gap detected"
        qa_section = qa_details
    else:
        qa_section = "- Not run"

    # Expert coverage section
    if expert_coverage is not None and expert_coverage.experts_consulted:
        expert_lines = []
        for exp in expert_coverage.experts_consulted:
            name = exp.get("name", "unknown")
            version = exp.get("version", "?")
            expert_lines.append(f"- {name} (v{version})")
        expert_list = "\n".join(expert_lines)
        triggers = (
            "\n".join(f"- {t}" for t in expert_coverage.policy_triggers)
            if expert_coverage.policy_triggers
            else "- None"
        )
        expert_section = f"{expert_list}\n\n**Policy triggers:**\n{triggers}"
    else:
        expert_section = "- No experts consulted"

    # Loopback summary section
    if loopback is not None:
        v_cats = (
            ", ".join(loopback.verification_failure_categories)
            if loopback.verification_failure_categories
            else "none"
        )
        q_cats = (
            ", ".join(loopback.qa_defect_categories)
            if loopback.qa_defect_categories
            else "none"
        )
        loopback_section = (
            f"- Verification loops: {loopback.verification_loop_count} (categories: {v_cats})\n"
            f"- QA loops: {loopback.qa_loop_count} (categories: {q_cats})"
        )
    else:
        loopback_section = "- No loopbacks"

    return f"""{EVIDENCE_COMMENT_MARKER}

## TheStudio Evidence

| Field | Value |
|-------|-------|
| **TaskPacket ID** | `{evidence.taskpacket_id}` |
| **Correlation ID** | `{correlation_id}` |
| **Intent Version** | v{evidence.intent_version} |
| **Verification** | {'PASSED' if verification.passed else 'FAILED'} |
| **QA** | {'PASSED' if qa_result and qa_result.passed else 'FAILED' if qa_result else 'N/A'} |

### Intent Summary

**Goal:** {intent.goal}

### Acceptance Criteria

{criteria_list}

### What Changed

{files_list}

### Verification Results

| Check | Result | Details |
|-------|--------|---------|
{checks_table}

### QA Result

{qa_section}

### Expert Coverage

{expert_section}

### Loopback Summary

{loopback_section}

---
*Generated by TheStudio — AI-augmented software delivery*
"""
