"""Evidence comment formatting for PR publication.

Formats the evidence comment that accompanies every draft PR.
Epic 0 format: TaskPacket ID, intent summary, verification result.
Full format (Epic 1): adds correlation_id, QA result, expert coverage, loopback summary.

Architecture reference: thestudioarc/15-system-runtime-flow.md — "Standard Agent Evidence Comment"
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from uuid import UUID

from src.agent.evidence import EvidenceBundle
from src.intent.intent_spec import IntentSpecRead
from src.publisher.evidence_payload import (
    CostBreakdown,
    EvidencePayload,
    GateResult,
    GateResults,
    IntentSummary,
    Provenance,
    ProvenanceEntry,
    TaskSummary,
)
from src.verification.gate import VerificationResult

# Marker used to identify TheStudio evidence comments for idempotent updates
EVIDENCE_COMMENT_MARKER = "<!-- thestudio-evidence -->"


def format_evidence_comment(
    evidence: EvidenceBundle,
    intent: IntentSpecRead,
    verification: VerificationResult,
) -> str:
    """Format the evidence comment for a draft PR.

    Contains: TaskPacket ID, intent summary, verification result.
    """
    # Verification summary
    check_lines = []
    for check in verification.checks:
        status = "PASSED" if check.passed else "FAILED"
        check_lines.append(f"| {check.name} | {status} | {check.details or '-'} |")
    checks_table = "\n".join(check_lines) if check_lines else "| - | - | - |"

    # Files changed
    files_list = (
        "\n".join(f"- `{f}`" for f in evidence.files_changed)
        if evidence.files_changed
        else "- None recorded"
    )

    # Acceptance criteria
    criteria_list = (
        "\n".join(f"- [ ] {c}" for c in intent.acceptance_criteria)
        if intent.acceptance_criteria
        else "- None specified"
    )

    return f"""{EVIDENCE_COMMENT_MARKER}

## TheStudio Evidence

| Field | Value |
|-------|-------|
| **TaskPacket ID** | `{evidence.taskpacket_id}` |
| **Intent Version** | v{evidence.intent_version} |
| **Loopback Attempts** | {evidence.loopback_attempt} |
| **Verification** | {'PASSED' if verification.passed else 'FAILED'} |

### Intent Summary

**Goal:** {intent.goal}

### Acceptance Criteria

{criteria_list}

### Verification Results

| Check | Result | Details |
|-------|--------|---------|
{checks_table}

### Files Changed

{files_list}

---
*Generated by TheStudio — AI-augmented software delivery*
"""


@dataclass
class PreflightSummary:
    """Summary of preflight plan review for the evidence comment.

    Epic 28 AC 11: Preflight result is included in evidence comment.
    """

    status: str = "skipped"  # "approved", "approved_after_replan", "skipped"
    summary: str = ""


@dataclass
class ApprovalMetadata:
    """Metadata about the approval decision for the evidence comment.

    Epic 24 Story 24.6 (AC #16): Approval decisions include channel
    and message count in the evidence comment.
    """

    decision: str = ""  # "approved" or "rejected"
    decided_by: str = ""
    channel: str = ""  # "api", "chat", "slack"
    review_message_count: int = 0


@dataclass
class ExpertCoverageSummary:
    """Summary of expert classes consulted and policy triggers."""

    experts_consulted: list[dict[str, object]] = field(default_factory=list)
    policy_triggers: list[str] = field(default_factory=list)


@dataclass
class LoopbackSummary:
    """Summary of verification and QA loopback history."""

    verification_loop_count: int = 0
    verification_failure_categories: list[str] = field(default_factory=list)
    qa_loop_count: int = 0
    qa_defect_categories: list[str] = field(default_factory=list)


@dataclass
class QAResultSummary:
    """Summary of QA validation result for the evidence comment."""

    passed: bool = False
    defect_count: int = 0
    defect_categories: list[str] = field(default_factory=list)
    has_intent_gap: bool = False


def format_full_evidence_comment(
    evidence: EvidenceBundle,
    intent: IntentSpecRead,
    verification: VerificationResult,
    correlation_id: UUID,
    qa_result: QAResultSummary | None = None,
    expert_coverage: ExpertCoverageSummary | None = None,
    loopback: LoopbackSummary | None = None,
    approval: ApprovalMetadata | None = None,
    preflight: PreflightSummary | None = None,
) -> str:
    """Format the full evidence comment per 15-system-runtime-flow.md.

    Required contents:
    - TaskPacket id and correlation id
    - Intent version and a one-paragraph summary
    - Acceptance criteria checklist (checkbox format)
    - What changed (high-level)
    - Verification result summary
    - QA result
    - Expert coverage summary
    - Loopback summary
    - Preflight result (Epic 28)
    """
    # Verification summary table
    check_lines = []
    for check in verification.checks:
        status = "PASSED" if check.passed else "FAILED"
        check_lines.append(f"| {check.name} | {status} | {check.details or '-'} |")
    checks_table = "\n".join(check_lines) if check_lines else "| - | - | - |"

    # Files changed
    files_list = (
        "\n".join(f"- `{f}`" for f in evidence.files_changed)
        if evidence.files_changed
        else "- None recorded"
    )

    # Acceptance criteria checklist
    criteria_list = (
        "\n".join(f"- [ ] {c}" for c in intent.acceptance_criteria)
        if intent.acceptance_criteria
        else "- None specified"
    )

    # QA result section
    if qa_result is not None:
        qa_status = "PASSED" if qa_result.passed else "FAILED"
        qa_details = f"**Result:** {qa_status}"
        if qa_result.defect_count > 0:
            cats = ", ".join(qa_result.defect_categories) if qa_result.defect_categories else "none"
            qa_details += f"\n- Defects: {qa_result.defect_count} ({cats})"
        if qa_result.has_intent_gap:
            qa_details += "\n- Intent gap detected"
        qa_section = qa_details
    else:
        qa_section = "- Not run"

    # Expert coverage section
    if expert_coverage is not None and expert_coverage.experts_consulted:
        expert_lines = []
        for exp in expert_coverage.experts_consulted:
            name = exp.get("name", "unknown")
            version = exp.get("version", "?")
            expert_lines.append(f"- {name} (v{version})")
        expert_list = "\n".join(expert_lines)
        triggers = (
            "\n".join(f"- {t}" for t in expert_coverage.policy_triggers)
            if expert_coverage.policy_triggers
            else "- None"
        )
        expert_section = f"{expert_list}\n\n**Policy triggers:**\n{triggers}"
    else:
        expert_section = "- No experts consulted"

    # Loopback summary section
    if loopback is not None:
        v_cats = (
            ", ".join(loopback.verification_failure_categories)
            if loopback.verification_failure_categories
            else "none"
        )
        q_cats = (
            ", ".join(loopback.qa_defect_categories)
            if loopback.qa_defect_categories
            else "none"
        )
        loopback_section = (
            f"- Verification loops: {loopback.verification_loop_count} (categories: {v_cats})\n"
            f"- QA loops: {loopback.qa_loop_count} (categories: {q_cats})"
        )
    else:
        loopback_section = "- No loopbacks"

    # Approval section (Epic 24 Story 24.6 AC #16)
    if approval is not None and approval.decision:
        approval_section = (
            f"**{approval.decision.title()}** by `{approval.decided_by}` "
            f"via {approval.channel}"
        )
        if approval.review_message_count > 0:
            approval_section += (
                f" after {approval.review_message_count} review messages"
            )
    else:
        approval_section = "- Pending"

    # Preflight section (Epic 28 AC 11)
    if preflight is not None:
        status_map = {
            "approved": "Approved",
            "approved_after_replan": "Approved after re-plan",
            "skipped": "Skipped (disabled)",
            "skipped_tier": "Skipped (tier not configured)",
        }
        preflight_label = status_map.get(preflight.status, preflight.status.title())
        preflight_section = f"**{preflight_label}**"
        if preflight.summary:
            preflight_section += f" — {preflight.summary}"
    else:
        preflight_section = "- Not configured"

    return f"""{EVIDENCE_COMMENT_MARKER}

## TheStudio Evidence

| Field | Value |
|-------|-------|
| **TaskPacket ID** | `{evidence.taskpacket_id}` |
| **Correlation ID** | `{correlation_id}` |
| **Intent Version** | v{evidence.intent_version} |
| **Verification** | {'PASSED' if verification.passed else 'FAILED'} |
| **QA** | {'PASSED' if qa_result and qa_result.passed else 'FAILED' if qa_result else 'N/A'} |

### Intent Summary

**Goal:** {intent.goal}

### Acceptance Criteria

{criteria_list}

### What Changed

{files_list}

### Verification Results

| Check | Result | Details |
|-------|--------|---------|
{checks_table}

### QA Result

{qa_section}

### Expert Coverage

{expert_section}

### Preflight

{preflight_section}

### Loopback Summary

{loopback_section}

### Approval

{approval_section}

---
*Generated by TheStudio — AI-augmented software delivery*
"""


# Nil UUID used as a sentinel when correlation_id is not available
_NIL_UUID = UUID("00000000-0000-0000-0000-000000000000")


def format_evidence_json(
    evidence: EvidenceBundle,
    intent: IntentSpecRead | None = None,
    verification: VerificationResult | None = None,
    correlation_id: UUID | None = None,
    repo: str = "",
    issue_id: int = 0,
    status: str = "unknown",
    trust_tier: str | None = None,
    pr_number: int | None = None,
    pr_url: str | None = None,
    qa_result: QAResultSummary | None = None,
    expert_coverage: ExpertCoverageSummary | None = None,
    loopback: LoopbackSummary | None = None,
    agent_model: str | None = None,
    cost_breakdown: CostBreakdown | None = None,
) -> EvidencePayload:
    """Generate a structured EvidencePayload JSON document for a TaskPacket.

    Extracts data from the EvidenceBundle, IntentSpec, VerificationResult, and
    optional supplementary inputs.  All optional parameters are handled
    gracefully — missing data is represented by None or empty defaults rather
    than raising errors.

    Args:
        evidence: EvidenceBundle from the Primary Agent (required).
        intent: IntentSpecRead for the task; omit if not yet available.
        verification: VerificationResult from the Verification Gate; omit if
            not yet run.
        correlation_id: Workflow correlation ID.  Defaults to nil UUID.
        repo: Repository slug (e.g. "org/repo").
        issue_id: GitHub issue number.
        status: Current TaskPacket status string.
        trust_tier: Trust tier string ("observe", "suggest", "execute").
        pr_number: Draft PR number if published.
        pr_url: Draft PR HTML URL if published.
        qa_result: QA gate summary; populates gate_results.qa_passed and
            defect fields when provided.
        expert_coverage: Expert coverage summary; maps to provenance section.
        loopback: Loopback history; maps to provenance.loopback_stages.
        agent_model: LLM model identifier used by the Primary Agent.
        cost_breakdown: Token/cost breakdown; passed through unchanged.

    Returns:
        EvidencePayload ready for JSON serialisation.
    """
    # ── TaskSummary ──────────────────────────────────────────────────────────
    task_summary = TaskSummary(
        taskpacket_id=evidence.taskpacket_id,
        correlation_id=correlation_id if correlation_id is not None else _NIL_UUID,
        repo=repo,
        issue_id=issue_id,
        status=status,
        trust_tier=trust_tier,
        loopback_count=evidence.loopback_attempt,
        created_at=evidence.created_at,
        pr_number=pr_number,
        pr_url=pr_url,
    )

    # ── IntentSummary ────────────────────────────────────────────────────────
    intent_summary: IntentSummary | None = None
    if intent is not None:
        intent_summary = IntentSummary(
            goal=intent.goal,
            version=intent.version,
            acceptance_criteria=list(intent.acceptance_criteria),
            constraints=list(intent.constraints),
            non_goals=list(intent.non_goals),
        )

    # ── GateResults ──────────────────────────────────────────────────────────
    gate_results: GateResults | None = None
    if verification is not None or qa_result is not None:
        checks: list[GateResult] = []
        verification_passed = False
        if verification is not None:
            verification_passed = verification.passed
            checks = [
                GateResult(
                    name=c.name,
                    passed=c.passed,
                    details=c.details or None,
                )
                for c in verification.checks
            ]
        qa_passed: bool | None = None
        defect_count = 0
        defect_categories: list[str] = []
        if qa_result is not None:
            qa_passed = qa_result.passed
            defect_count = qa_result.defect_count
            defect_categories = list(qa_result.defect_categories)
        gate_results = GateResults(
            verification_passed=verification_passed,
            qa_passed=qa_passed,
            checks=checks,
            defect_count=defect_count,
            defect_categories=defect_categories,
        )

    # ── Provenance ───────────────────────────────────────────────────────────
    provenance: Provenance | None = None
    if agent_model is not None or expert_coverage is not None or loopback is not None:
        experts: list[ProvenanceEntry] = []
        if expert_coverage is not None:
            for exp in expert_coverage.experts_consulted:
                experts.append(
                    ProvenanceEntry(
                        name=str(exp.get("name", "unknown")),
                        version=str(exp["version"]) if "version" in exp else None,
                        role=str(exp["role"]) if "role" in exp else None,
                        policy_triggers=[
                            str(t) for t in exp.get("policy_triggers", [])  # type: ignore[union-attr]
                        ],
                    )
                )
        loopback_stages: list[str] = []
        if loopback is not None:
            loopback_stages = list(loopback.verification_failure_categories) + list(
                loopback.qa_defect_categories
            )
        provenance = Provenance(
            experts_consulted=experts,
            agent_model=agent_model,
            loopback_stages=loopback_stages,
        )

    return EvidencePayload(
        schema_version="1.0",
        generated_at=datetime.now(UTC),
        task_summary=task_summary,
        intent=intent_summary,
        gate_results=gate_results,
        cost_breakdown=cost_breakdown,
        provenance=provenance,
        files_changed=list(evidence.files_changed),
    )
